version: '3'
services:
  mysql:
    image: mysql
    container_name: gengar.mysql
    volumes:
      - "mysql-data:/var/lib/mysql/:delegated"
      - "./docker/mysql/init:/docker-entrypoint-initdb.d"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
volumes:
  mysql-data:
    driver: local
